import {useCallback,useEffect,useState} from 'react'
import {ArrowLeft,Check,CreditCard,History,Home,LogOut,Plus,Scale,Settings,Sun,Moon,Trash2,Users,X,Pencil,WifiOff,RefreshCw,User} from 'lucide-react'
import {calculateBalances,money,simplifyDebts} from './lib/finance'
import {loadData,saveData} from './lib/storage'
import {detectLocalV1} from './lib/localV1'
import {config,supabase} from './lib/supabase'
import * as api from './lib/api'
import {subscribeToGroup} from './lib/realtime'

const colors=['#6c5ce7','#00b894','#e17055','#0984e3','#e84393','#fdcb6e']
function Avatar({member,small=false}){return <span className={`avatar ${small?'small':''}`} style={{background:member?.color||colors[0]}}>{member?.name?.[0]?.toUpperCase()||'?'}</span>}
function Modal({title,onClose,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="sheet"><header><h2>{title}</h2><button className="icon" onClick={onClose} aria-label="Закрыть"><X/></button></header>{children}</div></div>}
function Empty({icon:Icon,title,text}){return <div className="empty"><Icon/><h3>{title}</h3><p>{text}</p></div>}
function Notice({type='',children}){return <div className={`notice ${type}`}>{children}</div>}

export default function App(){
 const [demo,setDemo]=useState(false)
 if(!config.configured&&!demo)return <ConfigRequired onDemo={()=>setDemo(true)}/>
 return demo?<DemoApp/>:<CloudApp/>
}
function ConfigRequired({onDemo}){const local=detectLocalV1();return <main className="app centered"><Top theme="light" setTheme={()=>{}}/><section className="auth-card"><Scale/><h1>Нужна настройка Supabase</h1><p>{config.reason}. Скопируйте <code>.env.example</code> в <code>.env</code> и перезапустите приложение.</p>{local.available&&<Notice>Найдены локальные данные Split v1: {local.count} групп. Они сохранены и будут доступны для импорта после входа.</Notice>}<button className="primary wide" onClick={onDemo}>Открыть локальный просмотр</button></section></main>}
function DemoApp(){const [data,setData]=useState(loadData);useEffect(()=>{saveData(data);document.documentElement.dataset.theme=data.theme},[data]);return <LocalGroups data={data} setData={setData}/>}
function LocalGroups({data,setData}){const [modal,setModal]=useState(false);return <main className="app"><Top theme={data.theme} setTheme={theme=>setData(d=>({...d,theme}))}/><Notice type="warning">Локальный просмотр Split v1: данные не изменяются, облачная синхронизация не настроена.</Notice><section className="hero"><span className="eyebrow">СОВМЕСТНЫЕ РАСХОДЫ</span><h1>Путешествовать лучше,<br/>когда делить расходы легко.</h1><p>Ваши данные v1 сохранены и готовы к импорту.</p></section><GroupList groups={data.groups} onOpen={()=>setModal(true)} onNew={()=>setModal(true)}/>{modal&&<Modal title="Локальный просмотр" onClose={()=>setModal(false)}><Notice>Для работы с группами настройте Supabase и войдите в аккаунт.</Notice></Modal>}<Bottom active="groups"/></main>}

function CloudApp(){
 const [session,setSession]=useState(null),[ready,setReady]=useState(false),[recovery,setRecovery]=useState(false)
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});const {data}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setRecovery(true)});return()=>data.subscription.unsubscribe()},[])
 if(!ready)return <Loading/>
 if(recovery&&session)return <Recovery done={()=>setRecovery(false)}/>
 if(!session)return <Auth/>
 return <CloudHome session={session}/>
}
function Auth(){const [mode,setMode]=useState('login'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');async function submit(e){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget),email=f.get('email'),password=f.get('password');let result;if(mode==='signup')result=await supabase.auth.signUp({email,password,options:{data:{display_name:f.get('name')}}});else if(mode==='reset')result=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin});else result=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error)setError(result.error.message);else if(mode!=='login')setMessage(mode==='signup'?'Проверьте почту для подтверждения регистрации.':'Ссылка для восстановления отправлена.')}
 return <main className="app centered"><Top theme="light" setTheme={()=>{}}/><section className="auth-card"><User/><h1>{mode==='signup'?'Регистрация':mode==='reset'?'Восстановление пароля':'Вход в Split'}</h1>{error&&<Notice type="error">{error}</Notice>}{message&&<Notice>{message}</Notice>}<form className="form" onSubmit={submit}>{mode==='signup'&&<label>Ваше имя<input name="name" required/></label>}<label>Email<input name="email" type="email" required autoComplete="email"/></label>{mode!=='reset'&&<label>Пароль<input name="password" type="password" minLength="6" required autoComplete={mode==='signup'?'new-password':'current-password'}/></label>}<button className="primary wide" disabled={busy}>{busy?'Подождите…':mode==='signup'?'Создать аккаунт':mode==='reset'?'Отправить ссылку':'Войти'}</button></form><div className="auth-links"><button onClick={()=>setMode(mode==='signup'?'login':'signup')}>{mode==='signup'?'Уже есть аккаунт':'Создать аккаунт'}</button><button onClick={()=>setMode(mode==='reset'?'login':'reset')}>{mode==='reset'?'Вернуться ко входу':'Забыли пароль?'}</button></div></section></main>}
function Recovery({done}){const [error,setError]=useState('');async function submit(e){e.preventDefault();const password=new FormData(e.currentTarget).get('password');const {error:failure}=await supabase.auth.updateUser({password});if(failure)setError(failure.message);else done()}return <main className="app centered"><Top theme="light" setTheme={()=>{}}/><section className="auth-card"><h1>Новый пароль</h1>{error&&<Notice type="error">{error}</Notice>}<form className="form" onSubmit={submit}><label>Пароль<input name="password" type="password" minLength="6" required autoComplete="new-password"/></label><button className="primary wide">Сохранить пароль</button></form></section></main>}
function Loading(){return <main className="app centered"><div className="loading"><RefreshCw className="spin"/>Загрузка…</div></main>}

function CloudHome({session}){
 const cacheKey=`split-cloud-cache:${session.user.id}`
 const cached=()=>{try{return JSON.parse(localStorage.getItem(cacheKey))||[]}catch{return []}}
 const [groups,setGroups]=useState(cached),[groupId,setGroupId]=useState(null),[modal,setModal]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[offline,setOffline]=useState(!navigator.onLine),[theme,setTheme]=useState(localStorage.getItem('split-theme-v2')||'light')
 const local=detectLocalV1()
 const refresh=useCallback(async()=>{try{setError('');const next=await api.loadGroups(supabase);setGroups(next);localStorage.setItem(cacheKey,JSON.stringify(next))}catch(e){setError(e.message)}finally{setBusy(false)}},[cacheKey])
 useEffect(()=>{refresh()},[refresh]);useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('split-theme-v2',theme)},[theme]);useEffect(()=>{const on=()=>setOffline(!navigator.onLine);addEventListener('online',on);addEventListener('offline',on);return()=>{removeEventListener('online',on);removeEventListener('offline',on)}},[])
 useEffect(()=>groupId?subscribeToGroup(supabase,groupId,refresh):undefined,[groupId,refresh])
 const run=async fn=>{try{setError('');await fn();await refresh();setModal(null)}catch(e){setError(e.message)}}
 const group=groups.find(g=>g.id===groupId)
 if(busy)return <Loading/>
 if(group)return <GroupDetail group={group} back={()=>setGroupId(null)} refresh={refresh} run={run} modal={modal} setModal={setModal} theme={theme} setTheme={setTheme} userId={session.user.id}/>
 return <main className="app"><Top theme={theme} setTheme={setTheme}/><Status offline={offline} error={error}/><section className="account"><span>{session.user.email}</span><button className="icon" aria-label="Профиль" onClick={()=>setModal('profile')}><User/></button><button className="icon" aria-label="Выйти" onClick={()=>supabase.auth.signOut()}><LogOut/></button></section>{local.available&&<Notice>Найдены данные Split v1: {local.count} групп. <button className="link-button" onClick={()=>setModal('import')}>Импортировать копию</button></Notice>}<section className="hero"><span className="eyebrow">СОВМЕСТНЫЕ РАСХОДЫ</span><h1>Путешествовать лучше,<br/>когда делить расходы легко.</h1><p>Группы синхронизируются между вашими устройствами.</p></section><GroupList groups={groups} onOpen={setGroupId} onNew={()=>setModal('new')}/><button className="fab" onClick={()=>setModal('new')}><Plus/></button><Bottom active="groups"/>
 {modal==='new'&&<Modal title="Новая группа" onClose={()=>setModal(null)}><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const result=await api.createGroup(supabase,f.get('name').trim(),f.get('currency'));setGroupId(result.group_id)})}}><label>Название<input name="name" required autoFocus/></label><label>Валюта<select name="currency"><option>EUR</option><option>USD</option><option>RUB</option></select></label><button className="primary wide">Создать</button></form><JoinForm run={run} setGroupId={setGroupId}/></Modal>}
 {modal==='profile'&&<Modal title="Профиль" onClose={()=>setModal(null)}><form className="form" onSubmit={e=>{e.preventDefault();run(()=>api.saveProfile(supabase,session.user.id,new FormData(e.currentTarget).get('name').trim()))}}><label>Отображаемое имя<input name="name" required defaultValue={session.user.user_metadata?.display_name||''}/></label><button className="primary wide">Сохранить</button></form></Modal>}
 {modal==='import'&&<Modal title="Импорт Split v1" onClose={()=>setModal(null)}><Notice>Будет создана облачная копия {local.count} групп. Исходные данные в localStorage останутся без изменений. Повторный импорт не создаст дубликаты.</Notice><button className="primary wide" onClick={()=>run(()=>api.importLocalV1(supabase,local.data))}>Импортировать</button></Modal>}</main>
}
function Status({offline,error}){return <>{offline&&<Notice type="warning"><WifiOff/> Нет сети. Показаны последние загруженные данные.</Notice>}{error&&<Notice type="error">Ошибка: {error}</Notice>}</>}
function GroupList({groups,onOpen,onNew}){return <><section className="section-head"><div><h2>Ваши группы</h2><p>{groups.length} активных</p></div><button className="primary" onClick={onNew}><Plus/> Новая группа</button></section><div className="groups">{groups.map(g=><button className="group-card" key={g.id} onClick={()=>onOpen(g.id)}><div className="cover">{g.name.slice(0,2).toUpperCase()}</div><div className="group-info"><h3>{g.name}</h3><p><Users/> {g.members.length} участников · <History/> {g.expenses.length} расходов</p><strong>{money(g.expenses.reduce((s,e)=>s+e.amount,0),g.currency)}</strong></div><span className="chev">›</span></button>)}</div>{!groups.length&&<Empty icon={Users} title="Групп пока нет" text="Создайте группу или присоединитесь по коду."/>}</>}
function JoinForm({run,setGroupId}){return <form className="form join" onSubmit={e=>{e.preventDefault();run(async()=>{const r=await api.joinGroup(supabase,new FormData(e.currentTarget).get('code'));setGroupId(r.group_id)})}}><h3>Присоединиться по коду</h3><label>Код приглашения<input name="code" required maxLength="12" autoCapitalize="characters"/></label><button className="primary wide">Присоединиться</button></form>}
function GroupDetail({group,back,run,modal,setModal,theme,setTheme,userId}){const [tab,setTab]=useState('expenses'),balances=calculateBalances(group),debts=simplifyDebts(group),isOwner=group.ownerId===userId;const outstanding=debts.filter(d=>!group.settlements.some(s=>s.fromId===d.fromId&&s.toId===d.toId&&Math.abs(s.amount-d.amount)<.01));const canEdit=e=>isOwner||e.createdBy===userId
 return <main className="app"><header className="detail-top"><button className="icon" onClick={back}><ArrowLeft/></button><div><h1>{group.name}</h1><p>{group.members.length} участников · {group.currency}</p></div><ThemeSwitch theme={theme} setTheme={setTheme} compact/><button className="icon" onClick={()=>setModal('settings')}><Settings/></button></header><div className="tabs"><button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}>Расходы</button><button className={tab==='balances'?'active':''} onClick={()=>setTab('balances')}>Балансы</button><button className={tab==='settlements'?'active':''} onClick={()=>setTab('settlements')}>Расчёты</button></div>
 {tab==='expenses'&&<><section className="summary"><span>Всего потрачено</span><strong>{money(group.expenses.reduce((s,e)=>s+e.amount,0),group.currency)}</strong><div className="faces">{group.members.map(m=><Avatar key={m.id} member={m}/>)}</div></section><section className="section-head"><div><h2>Последние расходы</h2><p>{group.expenses.length} записей</p></div><button className="primary" disabled={!group.members.length} onClick={()=>setModal({expense:null})}><Plus/> Добавить</button></section><div className="list">{group.expenses.map(e=>{const payer=group.members.find(m=>m.id===e.payerId);return <article className="expense" key={e.id}><div className="expense-icon"><CreditCard/></div><div className="grow"><h3>{e.description}</h3><p><Avatar small member={payer}/>{payer?.name} заплатил(а) · {new Date(e.date+'T12:00').toLocaleDateString('ru-RU')}</p></div><div className="amount"><strong>{money(e.amount,group.currency)}</strong><small>{e.participantIds.length} участников</small></div>{canEdit(e)&&<button className="icon tiny" onClick={()=>setModal({expense:e})}><Pencil/></button>}</article>})}{!group.expenses.length&&<Empty icon={History} title="Расходов пока нет" text="Добавьте первый совместный расход."/>}</div></>}
 {tab==='balances'&&<><section className="page-title"><h2>Балансы</h2><p>Кто сколько заплатил и должен</p></section><div className="balance-grid">{group.members.map(m=>{const b=balances[m.id];return <article className="balance-card" key={m.id}><div className="person"><Avatar member={m}/><div><h3>{m.name}</h3><span className={b.net>=0?'positive':'negative'}>{b.net>=0?'получит ':'должен '}{money(Math.abs(b.net),group.currency)}</span></div></div><div className="metrics"><div><span>Оплачено</span><strong>{money(b.paid,group.currency)}</strong></div><div><span>Доля</span><strong>{money(b.owed,group.currency)}</strong></div><div><span>К получению</span><strong>{money(Math.max(0,b.net),group.currency)}</strong></div></div></article>})}</div></>}
 {tab==='settlements'&&<><section className="page-title"><h2>Кто кому должен</h2><p>Долги упрощаются автоматически</p></section><div className="settle-list">{outstanding.map(d=>{const from=group.members.find(m=>m.id===d.fromId),to=group.members.find(m=>m.id===d.toId);return <article className="settlement" key={d.fromId+d.toId}><div className="route"><Avatar member={from}/><span>→</span><Avatar member={to}/></div><div className="grow"><h3>{from?.name} → {to?.name}</h3><strong>{money(d.amount,group.currency)}</strong></div><button className="done" onClick={()=>run(()=>api.addSettlement(supabase,group.id,d))}><Check/> Оплачено</button></article>})}{!outstanding.length&&<Empty icon={Check} title="Все расчёты завершены!" text="Непогашенных переводов нет."/>}</div></>}
 {modal?.expense!==undefined&&<ExpenseModal group={group} expense={modal.expense} close={()=>setModal(null)} save={(e,old)=>{e.preventDefault();const f=new FormData(e.currentTarget),participantIds=f.getAll('participants');if(!participantIds.length)return;run(()=>api.saveExpense(supabase,group.id,{id:old?.id,description:f.get('description').trim(),amount:Number(f.get('amount')),payerId:f.get('payer'),participantIds,date:f.get('date')}))}} remove={modal.expense?()=>run(()=>api.deleteExpense(supabase,modal.expense.id)):null}/>} 
 {modal==='settings'&&<Modal title="Группа и участники" onClose={()=>setModal(null)}><Notice>Код приглашения даёт зарегистрированному пользователю доступ к группе и создаёт связанного участника.</Notice><div className="invite-code">{group.inviteCode}</div><div className="member-list">{group.members.map(m=><div className="person" key={m.id}><Avatar member={m}/><div><h3>{m.name}</h3><span>{m.userId?'Аккаунт Split':'Локальный участник группы'}</span></div></div>)}</div><form className="form join" onSubmit={e=>{e.preventDefault();run(()=>api.addMember(supabase,group.id,new FormData(e.currentTarget).get('name'))) }}><h3>Добавить участника без аккаунта</h3><label>Имя<input name="name" required maxLength="80"/></label><button className="primary wide">Добавить</button></form></Modal>}
 <button className="fab" disabled={!group.members.length} onClick={()=>setModal({expense:null})}><Plus/></button><Bottom active={tab} set={setTab}/></main>}
function ExpenseModal({group,expense,close,save,remove}){return <Modal title={expense?'Изменить расход':'Добавить расход'} onClose={close}><form className="form" onSubmit={e=>save(e,expense)}><label>Описание<input name="description" required autoFocus defaultValue={expense?.description}/></label><div className="split-fields"><label>Сумма<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={expense?.amount}/></label><label>Дата<input name="date" type="date" required defaultValue={expense?.date||new Date().toISOString().slice(0,10)}/></label></div><label>Кто заплатил<select name="payer" defaultValue={expense?.payerId}>{group.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><fieldset><legend>Разделить поровну между</legend>{group.members.map(m=><label className="check" key={m.id}><input type="checkbox" name="participants" value={m.id} defaultChecked={!expense||expense.participantIds.includes(m.id)}/><Avatar small member={m}/><span>{m.name}</span><Check/></label>)}</fieldset><button className="primary wide">Сохранить</button>{remove&&<button type="button" className="danger wide" onClick={remove}><Trash2/> Удалить расход</button>}</form></Modal>}
function ThemeSwitch({theme,setTheme,compact=false}){return <div className={`theme-switch ${compact?'compact':''}`} role="group" aria-label="Тема оформления"><button type="button" className={theme==='light'?'active':''} aria-pressed={theme==='light'} onClick={()=>setTheme('light')}><Sun/><span>Светлая</span></button><button type="button" className={theme==='dark'?'active':''} aria-pressed={theme==='dark'} onClick={()=>setTheme('dark')}><Moon/><span>Тёмная</span></button></div>}
function Top({theme,setTheme}){return <header className="top"><div className="brand"><span><Scale/></span>Split</div><ThemeSwitch theme={theme} setTheme={setTheme}/></header>}
function Bottom({active,set}){return <nav className="bottom"><button className={active==='groups'?'active':''}><Home/><span>Группы</span></button>{set&&<><button className={active==='expenses'?'active':''} onClick={()=>set('expenses')}><History/><span>Расходы</span></button><button className={active==='balances'?'active':''} onClick={()=>set('balances')}><Scale/><span>Балансы</span></button><button className={active==='settlements'?'active':''} onClick={()=>set('settlements')}><Check/><span>Расчёты</span></button></>}</nav>}
