import {useEffect,useState} from 'react'
import {ArrowLeft,Check,CreditCard,History,Home,Plus,Scale,Settings,Sun,Moon,Trash2,Users,X,Pencil} from 'lucide-react'
import {calculateBalances,money,simplifyDebts} from './lib/finance'
import {loadData,saveData} from './lib/storage'

const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random())
const colors=['#6c5ce7','#00b894','#e17055','#0984e3','#e84393','#fdcb6e']
function Avatar({member,small=false}){return <span className={`avatar ${small?'small':''}`} style={{background:member?.color||colors[0]}}>{member?.name?.[0]?.toUpperCase()||'?'}</span>}
function Modal({title,onClose,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="sheet"><header><h2>{title}</h2><button className="icon" onClick={onClose} aria-label="Закрыть"><X/></button></header>{children}</div></div>}
function Empty({icon:Icon,title,text}){return <div className="empty"><Icon/><h3>{title}</h3><p>{text}</p></div>}

export default function App(){
 const [data,setData]=useState(loadData);const [groupId,setGroupId]=useState(null);const [tab,setTab]=useState('expenses');const [modal,setModal]=useState(null);const group=data.groups.find(g=>g.id===groupId)
 useEffect(()=>{saveData(data);document.documentElement.dataset.theme=data.theme},[data])
 const updateGroup=fn=>setData(d=>({...d,groups:d.groups.map(g=>g.id===groupId?fn(g):g)}))
 const setTheme=theme=>setData(d=>({...d,theme}))
 const createGroup=e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=uid();setData(d=>({...d,groups:[...d.groups,{id,name:f.get('name').trim(),currency:f.get('currency'),members:[],expenses:[],settlements:[]}]}));setModal(null);setGroupId(id)}
 const deleteGroup=()=>{if(confirm(`Удалить группу «${group.name}»?`)){setData(d=>({...d,groups:d.groups.filter(g=>g.id!==groupId)}));setGroupId(null)}}
 if(!group)return <main className="app"><Top theme={data.theme} setTheme={setTheme}/><section className="hero"><span className="eyebrow">СОВМЕСТНЫЕ РАСХОДЫ</span><h1>Путешествовать лучше,<br/>когда делить расходы легко.</h1><p>Создайте группу, добавьте расходы, а расчёты мы возьмём на себя.</p></section><section className="section-head"><div><h2>Ваши группы</h2><p>{data.groups.length} активных</p></div><button className="primary" onClick={()=>setModal('group')}><Plus/> Новая группа</button></section><div className="groups">{data.groups.map(g=>{const total=g.expenses.reduce((s,e)=>s+Number(e.amount),0);return <button className="group-card" key={g.id} onClick={()=>setGroupId(g.id)}><div className="cover">{g.name.slice(0,2).toUpperCase()}</div><div className="group-info"><h3>{g.name}</h3><p><Users/> {g.members.length} участников · <History/> {g.expenses.length} расходов</p><strong>{money(total,g.currency)}</strong></div><span className="chev">›</span></button>})}</div>{!data.groups.length&&<Empty icon={Users} title="Групп пока нет" text="Создайте группу, чтобы начать делить расходы."/>}<button className="fab" onClick={()=>setModal('group')}><Plus/></button>{modal==='group'&&<Modal title="Создать группу" onClose={()=>setModal(null)}><form onSubmit={createGroup} className="form"><label>Название группы<input name="name" required autoFocus placeholder="Например, поездка в Японию"/></label><label>Валюта<select name="currency"><option>EUR</option><option>USD</option><option>RUB</option></select></label><button className="primary wide">Создать группу</button></form></Modal>}<Bottom active="groups"/></main>
 const balances=calculateBalances(group);const debts=simplifyDebts(group);const outstanding=debts.filter(d=>!group.settlements.some(s=>s.fromId===d.fromId&&s.toId===d.toId&&Math.abs(s.amount-d.amount)<.01))
 const addMember=e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name').trim();updateGroup(g=>({...g,members:[...g.members,{id:uid(),name,color:colors[g.members.length%colors.length]}]}));setModal(null)}
 const saveExpense=(e,editing)=>{e.preventDefault();const f=new FormData(e.currentTarget),participants=f.getAll('participants');const expense={id:editing?.id||uid(),description:f.get('description').trim(),amount:Number(f.get('amount')),payerId:f.get('payer'),participantIds:participants,date:f.get('date')};if(!participants.length)return alert('Выберите хотя бы одного участника');updateGroup(g=>({...g,expenses:editing?g.expenses.map(x=>x.id===editing.id?expense:x):[expense,...g.expenses]}));setModal(null)}
 return <main className="app"><header className="detail-top"><button className="icon" onClick={()=>setGroupId(null)}><ArrowLeft/></button><div><h1>{group.name}</h1><p>{group.members.length} участников · {group.currency}</p></div><ThemeSwitch theme={data.theme} setTheme={setTheme} compact/><button className="icon" aria-label="Настройки группы" onClick={()=>setModal('settings')}><Settings/></button></header><div className="tabs"><button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}>Расходы</button><button className={tab==='balances'?'active':''} onClick={()=>setTab('balances')}>Балансы</button><button className={tab==='settlements'?'active':''} onClick={()=>setTab('settlements')}>Расчёты</button></div>
 {tab==='expenses'&&<><section className="summary"><span>Всего потрачено</span><strong>{money(group.expenses.reduce((s,e)=>s+Number(e.amount),0),group.currency)}</strong><div className="faces">{group.members.map(m=><Avatar key={m.id} member={m}/>) }<button onClick={()=>setModal('member')}><Plus/></button></div></section><section className="section-head"><div><h2>Последние расходы</h2><p>{group.expenses.length} записей</p></div><button className="primary" disabled={!group.members.length} onClick={()=>setModal({expense:null})}><Plus/> Добавить</button></section><div className="list">{group.expenses.map(e=>{const payer=group.members.find(m=>m.id===e.payerId);return <article className="expense" key={e.id}><div className="expense-icon"><CreditCard/></div><div className="grow"><h3>{e.description}</h3><p><Avatar small member={payer}/>{payer?.name} заплатил(а) · {new Date(e.date+'T12:00').toLocaleDateString('ru-RU',{month:'short',day:'numeric'})}</p></div><div className="amount"><strong>{money(e.amount,group.currency)}</strong><small>{e.participantIds.length} участников</small></div><button className="icon tiny" aria-label="Изменить" onClick={()=>setModal({expense:e})}><Pencil/></button></article>})}{!group.expenses.length&&<Empty icon={History} title="Расходов пока нет" text="Добавьте первый совместный расход."/>}</div></>}
 {tab==='balances'&&<><section className="page-title"><h2>Балансы</h2><p>Кто сколько заплатил и должен</p></section><div className="balance-grid">{group.members.map(m=>{const b=balances[m.id];return <article className="balance-card" key={m.id}><div className="person"><Avatar member={m}/><div><h3>{m.name}</h3><span className={b.net>=0?'positive':'negative'}>{b.net>=0?'получит ':'должен '}{money(Math.abs(b.net),group.currency)}</span></div></div><div className="metrics"><div><span>Оплачено</span><strong>{money(b.paid,group.currency)}</strong></div><div><span>Доля</span><strong>{money(b.owed,group.currency)}</strong></div><div><span>К получению</span><strong>{money(Math.max(0,b.net),group.currency)}</strong></div></div></article>})}</div>{!group.members.length&&<Empty icon={Scale} title="Балансов пока нет" text="Сначала добавьте участников и расходы."/>}</>}
 {tab==='settlements'&&<><section className="page-title"><h2>Кто кому должен</h2><p>Долги упрощаются автоматически</p></section><div className="settle-list">{outstanding.map(d=>{const from=group.members.find(m=>m.id===d.fromId),to=group.members.find(m=>m.id===d.toId);return <article className="settlement" key={d.fromId+d.toId}><div className="route"><Avatar member={from}/><span>→</span><Avatar member={to}/></div><div className="grow"><h3>{from.name} → {to.name}</h3><strong>{money(d.amount,group.currency)}</strong></div><button className="done" onClick={()=>updateGroup(g=>({...g,settlements:[...g.settlements,{...d,id:uid(),date:new Date().toISOString()}]}))}><Check/> Оплачено</button></article>})}{!outstanding.length&&<Empty icon={Check} title="Все расчёты завершены!" text="Непогашенных переводов нет."/>}{group.settlements.length>0&&<><h3 className="subhead">Завершённые</h3>{group.settlements.map(s=><article className="completed" key={s.id}><Check/><span>{group.members.find(m=>m.id===s.fromId)?.name} заплатил(а) {group.members.find(m=>m.id===s.toId)?.name}</span><strong>{money(s.amount,group.currency)}</strong></article>)}</>}</div></>}
 {modal==='member'&&<Modal title="Добавить участника" onClose={()=>setModal(null)}><form className="form" onSubmit={addMember}><label>Имя<input name="name" required autoFocus placeholder="Имя друга"/></label><button className="primary wide">Добавить участника</button></form></Modal>}
 {modal?.expense!==undefined&&<ExpenseModal group={group} expense={modal.expense} close={()=>setModal(null)} save={saveExpense} remove={modal.expense?()=>{updateGroup(g=>({...g,expenses:g.expenses.filter(e=>e.id!==modal.expense.id)}));setModal(null)}:null}/>} 
 {modal==='settings'&&<Modal title="Настройки группы" onClose={()=>setModal(null)}><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);updateGroup(g=>({...g,name:f.get('name'),currency:f.get('currency')}));setModal(null)}}><label>Название<input name="name" defaultValue={group.name} required/></label><label>Валюта<select name="currency" defaultValue={group.currency}><option>EUR</option><option>USD</option><option>RUB</option></select></label><button className="primary wide">Сохранить</button><button type="button" className="danger wide" onClick={deleteGroup}><Trash2/> Удалить группу</button></form></Modal>}
 <button className="fab" disabled={!group.members.length} onClick={()=>setModal({expense:null})}><Plus/></button><Bottom active={tab} set={setTab}/></main>
}
function ExpenseModal({group,expense,close,save,remove}){return <Modal title={expense?'Изменить расход':'Добавить расход'} onClose={close}><form className="form" onSubmit={e=>save(e,expense)}><label>Описание<input name="description" required autoFocus defaultValue={expense?.description} placeholder="На что потратили?"/></label><div className="split-fields"><label>Сумма<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={expense?.amount}/></label><label>Дата<input name="date" type="date" required defaultValue={expense?.date||new Date().toISOString().slice(0,10)}/></label></div><label>Кто заплатил<select name="payer" defaultValue={expense?.payerId}>{group.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><fieldset><legend>Разделить поровну между</legend>{group.members.map(m=><label className="check" key={m.id}><input type="checkbox" name="participants" value={m.id} defaultChecked={!expense||expense.participantIds.includes(m.id)}/><Avatar small member={m}/><span>{m.name}</span><Check/></label>)}</fieldset><button className="primary wide">{expense?'Сохранить изменения':'Добавить расход'}</button>{remove&&<button type="button" className="danger wide" onClick={remove}><Trash2/> Удалить расход</button>}</form></Modal>}
function ThemeSwitch({theme,setTheme,compact=false}){return <div className={`theme-switch ${compact?'compact':''}`} role="group" aria-label="Тема оформления"><button type="button" className={theme==='light'?'active':''} aria-pressed={theme==='light'} onClick={()=>setTheme('light')}><Sun/><span>Светлая</span></button><button type="button" className={theme==='dark'?'active':''} aria-pressed={theme==='dark'} onClick={()=>setTheme('dark')}><Moon/><span>Тёмная</span></button></div>}
function Top({theme,setTheme}){return <header className="top"><div className="brand"><span><Scale/></span>Split</div><ThemeSwitch theme={theme} setTheme={setTheme}/></header>}
function Bottom({active,set}){return <nav className="bottom"><button className={active==='groups'?'active':''}><Home/><span>Группы</span></button>{set&&<><button className={active==='expenses'?'active':''} onClick={()=>set('expenses')}><History/><span>Расходы</span></button><button className={active==='balances'?'active':''} onClick={()=>set('balances')}><Scale/><span>Балансы</span></button><button className={active==='settlements'?'active':''} onClick={()=>set('settlements')}><Check/><span>Расчёты</span></button></>}</nav>}
